<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net8.0;net10.0-android;net10.0-ios;net10.0-browser;</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net10.0-ios'">13.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net10.0-android'">26.0</SupportedOSPlatformVersion>
    <Nullable>annotations</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <IsBrowser>$([System.String]::Copy('$(TargetFramework)').Contains('-browser'))</IsBrowser>
    <DefineConstants Condition="'$(TargetFramework)' == 'net8.0'">$(DefineConstants);INCLUDE_WINDOWS;INCLUDE_LINUX</DefineConstants>
    <!-- ModuleInitializer in microcom codegen -->
    <NoWarn>$(NoWarn);CA2255</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsBrowser)' == 'true'">
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Windows/WinRT/windows.ui.notifications.mcidl" />
    <AdditionalFiles Include="Linux/DBusXml/org.freedesktop.portal.Notification.xml" DBusGeneratorMode="Proxy" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' AND '$(IsBrowser)' == 'false'">
    <PackageReference Include="Tmds.DBus.Protocol" />
    <PackageReference Include="Tmds.DBus.SourceGenerator" PrivateAssets="all" />
    <PackageReference Include="MicroCom.CodeGenerator.Roslyn" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0-android' ">
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsBrowser)' == 'true'">
    <ServiceWorker Include="wwwroot\notifications-service-worker.js" PublishedContent="wwwroot\notifications-service-worker-published.js" />
  </ItemGroup>
</Project>
